[platformio]
default_envs = nc01

[env:nc01]
platform = espressif32@6.12.0
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600
board_upload.flash_size = 16MB
board_build.flash_size = 16MB
board_build.partitions = partitions.csv
board_build.filesystem = littlefs
lib_ldf_mode = deep+
lib_deps =
  bodmer/TFT_eSPI@2.5.43
  h2zero/NimBLE-Arduino@2.5.0
  bblanchon/ArduinoJson@7.4.2
build_flags =
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DCORE_DEBUG_LEVEL=1
  -DUSER_SETUP_LOADED=1
  -DGC9A01_DRIVER=1
  -DTFT_WIDTH=240
  -DTFT_HEIGHT=240
  -DTFT_MOSI=11
  -DTFT_SCLK=10
  -DTFT_CS=9
  -DTFT_DC=8
  -DTFT_RST=12
  -DTFT_BL=40
  -DTFT_BACKLIGHT_ON=HIGH
  -DTOUCH_CS=-1
  -DSPI_FREQUENCY=40000000
  -DSPI_READ_FREQUENCY=20000000
  -DLOAD_GLCD=1
  -DLOAD_FONT2=1
